name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - release/*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: debug
      run: echo ${{ github.ref_name }} ${{ github.ref }} ${{ github.head_ref }}
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    
