name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: debug
      run: echo ${{ github.ref_name }} ${{ github.ref }} ${{ github.head_ref }}
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' 
        --repo '${{ github.repository }}'
    
